<?php
/**
 * @file
 */


/**
 * Implements hook_form_alter().
 */
function vih_core_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'mailchimp_lists_user_subscribe_form_nyhedsbrev') {
    if (module_exists('google_analytics')) {
      $form['#attached'] = array(
        'js' => array(
          '(function($){
$("#mailchimp-lists-user-subscribe-form-nyhedsbrev").submit(function(e){
if (typeof _gaq !== "undefined") {
// Category - Action - Event
_gaq.push(["_trackEvent", "Newsletter", "Subscribe", "DK"]);
}
})
})(jQuery);' => array('type' => 'inline')
        )
      );
    }
    $form['actions']['submit']['#value'] = 'Tilmeld';
  }
  elseif ($form_id == 'mailchimp_lists_user_subscribe_form_newsletter') {
    if (module_exists('google_analytics')) {
      $form['#attached'] = array(
        'js' => array(
          '(function($){
$("#mailchimp_lists_user_subscribe_form_newsletter").submit(function(e){
if (typeof _gaq !== "undefined") {
// Category - Action - Event
_gaq.push(["_trackEvent", "Newsletter", "Subscribe", "UK"]);
}
})
})(jQuery);' => array('type' => 'inline')
        )
      );
    }
    $form['actions']['submit']['#value'] = 'Subscribe';
  }
  return $form;
}

/**
 * Implements hook_update_projects_alter().
 */
function vih_core_update_projects_alter(&$projects) {
  // We wish to remove our custom modules from any drupal.org updates.
  foreach($projects as $key => $project) {
    // Most custom module match this naming convention.
    if (preg_match('/^vih_.*$/', $key)) {
      unset($projects[$key]);
    }
  }
}

/**
 * Returns the proper formats based on locale.
 *
 * @param string $locale
 *
 * @return mixed
 */
function vih_core_locale_date_formats($locale = NULL) {
  // DA.
  $formats['da'] = array(
    'panopoly_time' => 'g:ia',
    'panopoly_day' => 'j. M Y',
    'long' => 'l, j. F, Y - H:i',
    'medium' => 'D, d-m-Y - H:i',
    'short' => 'd-m-Y - H:i',
    'long_date_without_time' => 'l, j. F Y',
    'month' => 'F',
    'medium_date_without_time' => 'j. F, Y',
  );
  // EN
  $formats['en'] = array(
    'panopoly_time' => 'g:ia',
    'panopoly_day' => 'F j, Y',
    'long' => 'l, j F, Y - H:i',
    'medium' => 'D, m/d/Y - H:i',
    'short' => 'd/m/Y - H:i',
    'long_date_without_time' => 'l, j. F Y',
    'month' => 'F',
    'medium_date_without_time' => 'j. F Y',
  );

  if ($locale && isset($formats[$locale])) {
    return $formats[$locale];
  }

  return $formats;
}

/**
 * Updates the locale date format configurations.
 */
function vih_core_locale_date_formats_save() {
  $formats = vih_core_locale_date_formats();
  foreach ($formats as $langcode => $lang_formats) {
    foreach ($lang_formats as $type => $format) {
      locale_date_format_save($langcode, $type, $format);
    }
  }
}
